services:

  googletest:
    image: googletest
    container_name: googletest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/work
    working_dir: /work
    tty: true
    command: /bin/bash
  